version: 2

sources:

  - name: silver

    database: agentic_db

    schema: silver

    tables:

      - name: customers

      - name: orders

      - name: order_items

      - name: order_payments

      - name: order_reviews

      - name: products

      - name: sellers

      - name: geolocation

      - name: product_category_translation

      - name: weather